### PR TITLE
feat: add `minitrace-futures` to support instrumentation for `futures`

### PR DESCRIPTION
**Pull request by iGxnon**
Changes:

- Add a crate `minitrace-futures`
- Add a trait `Instrumented`
  - Provide `in_span` instrumentation.
  
Checklist:

- [x] Support `futures` 0.3.x
- [ ] Support `futures` 0.1.x

### CODE REVIEW

**Comment by iGxnon** [comment]
How should I fill in the `author` field in the `Cargo.toml` file?

**Comment by andylokandy** [comment]
I've a question about the `maker`: what is the proper way to use `maker`? For example, `Sink` has 4 methods to create span on poll, and the `maker` has no way to know which is called. And when get called, is local parent available?

**Comment by iGxnon** [comment]
> `Sink` has 4 methods to create span on poll, and the `maker` has no way to know which is called.

Perhaps replace `maker` in `enter_on_poll()` with `FnMut(&str) -> Span`?

> And will a local parent available when get called?

Can `set_local_parent` be left for the user to decide?

```rust
let mut drain = sink::drain().enter_on_poll(|| {
        let span = Span::enter_with_parent("SubTask" &root);
        // Set the local parent so that `LocalSpan`
        // becomes available in the sink.
        (span.set_local_parent(), span)
});
```

or

```rust
let mut drain = sink::drain().enter_on_poll(||  Span::enter_with_parent("SubTask" &root));
```

**Comment by andylokandy** [comment]
This seems too complicated. Maybe we could break it down. Perhaps a `use_root` field to indicate` EnterOnItem` to create a root span for each item? Perhaps `in_span` and `enter_on_poll` can be removed since meaningless.

**Comment by iGxnon** [comment]
> This seems too complicated, and maybe we could break it down

OK, let's confirm the approximate API first.

> Perhaps a `use_root` field to indicate` EnterOnItem` to create a root span for each item?

It can be done with:
```rust
let s = stream! {
        for i in 0..2 {
            yield i;
        }
}
.enter_on_item(|| Span::root("Root", SpanContext::random()));
```

In my scenario, I want to create a span for the user from the end of the last request to the receipt of the next request data. I hope this span can also collect some log events from the codec layer (the span needs to be the local parent), and it is best to report them as early as possible (the span is a root span). And I found that the duration of this span can be used to calculate a user's request frequency.

image

However, in fact, what I would prefer to do is to calculate the time consumed by the codec layer. It seems difficult to achieve without modifying the Item types of Stream and Sink. 

If I want to fully customize the lifetime of the span, then need to change the type of Stream and Sink Item to the following:

```rust
enum Item<T> {
    StartSpan,
    EndSpan,
    Item(T),
}
```

The instrumentation layer opens a span upon receiving `StartSpan` and ends the span upon receiving `EndSpan`.

For some simple stream or sink, 

> Perhaps `in_span` and `enter_on_poll` can be removed since meaningless.

For some simple streams or sinks, such as a snapshot stream that closes after complete reception, we can use `in_span` to handle it. The `enter_on_poll` is designed to provide an API similar to `FutureExt` and it could be removed.

**Comment by andylokandy** [comment]
> It can be done with:
```rust
let s = stream! {
        for i in 0..2 {
            yield i;
        }
}
.enter_on_item(|| Span::root("Root", SpanContext::random()));
```

I mean, instead of a flexible but error-prone `maker`, a specialized `use_root` is better, if the only thing we want is to switch between `Span` and root span.

> However, in fact, what I would prefer to do is to calculate the time consumed by the codec layer. It seems difficult to achieve without modifying the Item types of Stream and Sink.

Maybe you can do it by implementing https://docs.rs/tokio-util/latest/tokio_util/codec/trait.Decoder.html?

**Comment by andylokandy** [comment]
`tracing-futures` will not create new span for items but only `enter` a span, which will last the entire lifetime of the steam/sink. It seems like `in_span` in minitrace.

**Comment by iGxnon** [comment]
There is another question: is `enter_on_item` still needed? If so, I will submit a new PR to try to constrain the `maker` solution.

**Comment by andylokandy** [comment]
> is enter_on_item still needed?

I believe it will prove valuable if we can precisely define the semantics of enter_on_item (specifically, determining the precise moment that is considered as enter_on_item) and also develop a concrete example or use case to illustrate its application.

**Review by andylokandy — APPROVED** [review]

**Comment by andylokandy** [comment]
@iGxnon Thank you!

**Pull request merged**
