### PR TITLE
delete tokio's unused features

### PR DESCRIPTION
**Pull request by shota-kizawa**
I delete unnecessary features to reduce build size.
(Perhaps replacing tokio with another library might improve performance.)

Can someone review this PR?

### CODE REVIEW

**Comment by andylokandy** [comment]
Please fix DCO according to https://github.com/tikv/minitrace-rust/pull/124/checks?check_run_id=5627892907.

> Perhaps replacing tokio with another library might improve performance

Since `tokio` is only linked to tests, it should not take effect on library performance. Anyway, this PR reduces the build time on the development environment. It's nice to have.

**Comment by kiibo382** [comment]
> Please fix DCO according to https://github.com/tikv/minitrace-rust/pull/124/checks?check_run_id=5627892907.
Oh,,, sorry, I fixed it.

> Since tokio is only linked to tests, it should not take effect on library performance. Anyway, this PR reduces the build time on the development environment. It's nice to have.
Thanks! Understood.

**Comment by kiibo382** [comment]
@andylokandy 

> Please fix DCO according to https://github.com/tikv/minitrace-rust/pull/124/checks?check_run_id=5627892907.

Oh,,, sorry, I fixed it.

> Since tokio is only linked to tests, it should not take effect on library performance. Anyway, this PR reduces the build time on the development environment. It's nice to have.

Thanks! I missed it. Understood.

**Review by andylokandy — APPROVED** [review]

**Review by zhongzc — APPROVED** [review]
Thanks

**Comment by andylokandy** [comment]
@zhongzc  The CI seems dead. Are you able to re-trigger it?

**Comment by zhongzc** [comment]
For re-triggering CI

**Comment by kiibo382** [comment]
Thank you!

**Pull request merged**
