### PR TITLE
feat: single thread mode

### PR DESCRIPTION
**Pull request by andylokandy**
Signed-off-by: Andy Lok <andylokandy@hotmail.com>

Closes https://github.com/tikv/minitrace-rust/issues/197

### CODE REVIEW

**Comment by dotansimha** [comment]
Using this PR along with wasm32 runtime, I get ` time not implemented on this platform` errors 🤔  Not sure what's the source of it. @andylokandy

**Comment by dotansimha** [comment]
maybe this one? https://github.com/tikv/minitrace-rust/blob/master/minitrace/src/collector/global_collector.rs#L211

**Comment by dotansimha** [comment]
@andylokandy ok with this commit https://github.com/dotansimha/minitrace-rust/commit/ca4ab0d29ae5bca85cc2569071c57766643d6ec4 , it seems to work and it does not fail on the `time` issue.

I'm trying to use `minitrace::flush` but at the moment I only get the root `Span` reported and all the rest are ignored 🤔 
My current structure is like that:

```
- root (Span::root)
	- `async fn` with #[trace]
	- `async fn` with #[trace] 
		- ... several `async fn`, some with `#[trace]` and some with `in_span`
	- sync `fn` with #[trace]
```

The macro seems to set `#[trace]` to use `in_span`:

image

🤔

**Comment by andylokandy** [comment]
did you set_local_parent()? and drop all spans before flush?

**Comment by dotansimha** [comment]
> did you set_local_parent()? and drop all spans before flush?

oops, I missed that 🤦  I added it now and it seems to work! 🎉 

So I think the only fix needed for PR is https://github.com/dotansimha/minitrace-rust/commit/ca4ab0d29ae5bca85cc2569071c57766643d6ec4

**Review by dotansimha — APPROVED** [review]

**Review by zhongzc — APPROVED** [review]

**Comment by dotansimha** [comment]
@andylokandy can we get this released to Crates? 👀 

Thank you

**Pull request merged**
