### PR TITLE
doc: Fix unaligned number in the charts

### PR DESCRIPTION
**Pull request by breezewish**
Previously I exported these SVG graph from Safari, which incorrectly added spaces for formatting purpose that causes the numbers to be not aligned. I reexported these SVG graph from Chrome / Edge and now they look good.

### CODE REVIEW

**Comment by zhongzc** [comment]
How about

image

**Comment by breeswish** [comment]
image

I'm not sure, but for me after moving these badges, they seems to be distractive, i.e. I'm harder to notice the real important links above these notable badges (Docs, Getting Started, ...).

**Comment by breeswish** [comment]
@andylokandy @sticnarf What do you think?

**Comment by breeswish** [comment]
image

I further reduced the badge size, hope they are less attractive.

**Comment by sticnarf** [comment]
The new svg looks great on my Firefox too.

A bit off-topic, anyone else thinks the padding here is too large?
image

**Comment by breeswish** [comment]
> The new svg looks great on my Firefox too.
> 
> A bit off-topic, anyone else thinks the padding here is too large?

Good catch. I introduced some more spacing lines after the initial links:

image

This makes these links more highlighted!

**Comment by zhongzc** [comment]
Prefer badges to be as close to the title as possible.

Would like to hear your reasons for laying out the badges this way.

**Comment by sticnarf** [comment]
> > The new svg looks great on my Firefox too.
> > A bit off-topic, anyone else thinks the padding here is too large?
> 
> Good catch. I introduced some more spacing lines after the initial links:
> 
> image
> 
> This makes these links more highlighted!

I was hoping to reduce the padding a bit... This looks tooooo spacious to me...

If you mean to highlight the links, is it a good idea to make them bold?

**Comment by breeswish** [comment]
> Prefer badges to be as close to the title as possible.
> 
> Would like to hear your reasons for laying out the badges this way.

The current arrangement is to make sure that initial links (Docs | Getting Started | Examples | FAQ) are notable enough, because in the rest of the README readers are hard to discover these information any more. See  https://github.com/tikv/minitrace-rust/pull/105#issuecomment-1058892229 for a bad example that the badges are more attractive and easily gain users focus. What do you think about the philosophy?

**Comment by sticnarf** [comment]
Another choice is like https://github.com/d3/d3, use a separate list for the resource links:
image

**Review by sticnarf — COMMENTED** [review]
LGTM

**Comment by andylokandy** [comment]
> A bit off-topic, anyone else thinks the padding here is too large?

Maybe the beget can be put between the padding?

**Review by Xuanwo — APPROVED** [review]

**Pull request merged**
